version: '3'
services:

  db:
    image: mongo:latest
    container_name: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: madadmin
      MONGO_INITDB_ROOT_PASSWORD: supersecretpassword
    ports:
      - 27017:27017
    restart: always
    volumes: 
      - mongo-data:/data/db

  api:
    image: rlmckenney/mad9124-pizza-shop:latest
    container_name: api
    ports:
      - 80:3030
      - 443:443
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - api-logs:/app/logs
      - certbot-webroot:/app/public/.well-known
      - certbot-letsencrypt:/etc/letsencrypt
    depends_on:
      - db
  
  certbot:
    image: rlmckenney/mad9124-certbot:latest
    container_name: certbot
    restart: always
    volumes:
      - certbot-webroot:/webroots/mad9124.rocks/.well-known
      - certbot-letsencrypt:/etc/letsencrypt

volumes:
  api-logs:
  mongo-data:
  certbot-webroot:
  certbot-letsencrypt: